### ISSUE TITLE
Last step

### ISSUE THREAD

**Issue by schlatersm** [16EAGLE/moveVis#11]
So I first went through this with my own data and couldn't get the last step to work, so I used your data and ran into the same issue. Everything works until the last step of code (last step being when you call on animate_move) and I get this error
Error in animate_move(data_ani, out_dir, conv_dir = conv_dir, tail_elements = 10,  : 
  object 'img_sub' not found

Thoughts? 
Thanks in advance
SS

**Comment by vestlink** [comment]
Did you pass something like this?

img_sub <- paste0("GPS fixes recorded by Andy Allan")

**Comment by schlatersm** [comment]
Hi, thanks for your reply.

So I actually figured it out and successfully made a GIF of some of my data.

I have a lot of data that I'm just playing around with and I have two more questions

I have one birds' migration I want to display and I can't get it past the data_ani step. Does that have something to do with the fact that there is only one individual? I checked that everything was formatted the same as my previous data sheet that was successful.

This was the error I got

Error in split.default(x = seq_len(nrow(x)), f = f, drop = drop, ...) :
  argument "f" is missing, with no default
In addition: Warning messages:
1: Unknown or uninitialised column: 'citation'.
2: Setting row names on a tibble is deprecated

I also had issues trying to display data from two different time periods? Does that not work, or do you have any suggestions on how to mitigate that?

Thank you for any help you can provide!

Shannon

________________________________

**Comment by 16EAGLE** [comment]
Try to rerun your code with the current github beta version of moveVis: 
```s
install.packages("devtools")
devtools::install_github("16EAGLE/moveVis")
library(moveVis)
```
Please post your code you use to call animate_move.

**Comment by schlatersm** [comment]
Hi again,

I noticed you updated the code on your website. I had previously been just reopening your website and copying and pasting the code as needed and don't have the old code saved. Could you possibly send me what you previously had on your website. I'm not sure what's different but I can't get the new code to work. I mostly need the old conv_dir step and the last step: animate_move()

Thanks in advance

SS

________________________________

**Comment by 16EAGLE** [comment]
I updated the "Getting started"-Section for the newest vesion 0.9.6 on CRAN. The only changes have been

```s
#Get libraries 
conv_dir <- get_libraries()

#Find out, which output file formats can be used
get_formats()
```

which was `conv_dir <- get_imconvert()` before, but the latter one should still work with the new version. Also, the keyword `out_format` that is present in the new example cannot be called from the old version 0.9.5.

Easiest would be if you first try to update your current moveVis version to version 0.9.6 via CRAN using `install.packages("moveVis")`. With that version, the example code should work.

**Comment by schlatersm** [comment]
Hi again,

I updated moveVis and am still having trouble. Did I previously need ImageMagick or ffmpeg? I can't seem to get them properly installed and the code won't run without them? I was fine with the quality of the outputs I had before so if there is a way to run the code without them as I had been previously please let me know what you suggest in moving forward.

Thanks in advance

SS

________________________________
