### ISSUE TITLE
font size and movie speed

### ISSUE THREAD

**Issue by sternidae** [16EAGLE/moveVis#14]
Thanks for your help with resolving the video export issues. I have two more questions regarding animate_move:

1) is there a way to increase the font size of the time_scale?

2) is there a way to control the speed at which the output movie plays? I have been tweaking the frames parameters but haven't found a way to effectively slow the movie down

Thanks so much for your ongoing assistance. This is a fun program!

**Comment by 16EAGLE** [comment]
Font sizes cannot be changed in the current version. I put the feature to the features list on [http://news.movevis.org](http://news.movevis.org) and will implement it in one of the next updates. 

Speed can be controlled using the `frames_fps` keyword (default = 25). If you would change this to 1, each frame would be displayed for 1 second.

**Comment by vestlink** [comment]
Maybe also an option to include the timestamp in the animation?

**Comment by 16EAGLE** [comment]
This is already implemented through the `time_scale` argument within `animate_move()`.

**Comment by 16EAGLE** [comment]
Argument `time_size` for adjusting the font size of the timestep display added with commit https://github.com/16EAGLE/moveVis/commit/0fd25c19eb3ecb7dfcc8ee74dca07c684562f4ac.
