### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by vestlink** [16EAGLE/moveVis#15]
move_data$dt <- as.POSIXct(strptime(move_data$dt, "\%Y-\%m-\%d \%H:\%M:\%S", tz = "UTC"))

gives this:

Error: '\%' is an unrecognized escape in character string starting ""\%"

move_data$dt <- as.POSIXct(strptime(move_data$dt, "%Y-%m-%d %H:%M:%S", tz = "UTC"))

does not

**Comment by vestlink** [comment]
maybe also alter or add this as a useful example:

#or to a temporary directory:
out_dir <- paste0(tempdir(),"/test")
dir.create(out_dir)

instead use this ?
out_dir <- paste0(getwd(),"/test")

**Comment by 16EAGLE** [comment]
Thank you! I will change the example and README code.
