### ISSUE TITLE
Error in creating vis with raster layer

### ISSUE THREAD

**Issue by anjankatna** [16EAGLE/moveVis#17]
Hi,
I am trying to create a vis with data for a single individual downloaded from movebank. I am able to create a gif with google basemap as layer. However, when I use and NDVI raster, I get the following error.

Duration of output animation file: 00:00:08 (hh:mm:ss) [173 frames, 25 fps]
Drawing frames...
   |==================================================================================| 100% elapsed = 03m 19s
Total run time: 5.12 minutes
Error: animate_move failed due to unknown error.
In addition: Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c D:/Programs/imagick/convert.exe' had status 1 
2: In cmd.fun(conv_dir, ignore.stdout = TRUE, ignore.stderr = TRUE) :
  'D:/Programs/imagick/convert.exe' execution failed with error code 1

**Comment by 16EAGLE** [comment]
Hi Anjan, sorry for the very late replay. Could not reproduce the error, but I am looking into the command recognition on windows platforms before the next release. Strange that it only occurs with a raster input. Unfortunately, I had no time to do so during the last months, will check it during next week.

**Comment by syanco** [comment]
I am getting this error as well - using my own data set but otherwise following the code in the example.  I've tried with different calls to basemaps and none seem to work.  Let me know if posting my script here would be helpful.

**Comment by 16EAGLE** [comment]
@syanco thanks for letting me know. Please be referred to issue #13
