### ISSUE TITLE
Error with animate_move... due to wrong subsetting?

### ISSUE THREAD

**Issue by serchenheim** [16EAGLE/moveVis#19]
Hi there, 

I've successfully created an animation using the example and sample data that you provide, but when I try to do it with my own data I'm getting this error:

Error in prog_x_st[1:prog_bar_length] : 
  only 0's may be mixed with negative subscripts

I'm not sure if this is the reason, but I found that this error may occur when "you get a vector with a mix of positive and negative values, which isn't allowed in subsetting." (https://stackoverflow.com/questions/9221310/r-debugging-only-0s-may-be-mixed-with-negative-subscripts?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

Would you have any idea on why this may be happening? I am attaching a sample of my data as an example. Thanks!

These are all the messages I get when I run the function:
Checking prerequisites...
Detected 'conv_dir' executable on this system: 'convert'
Paths interpolation will be applied, since 'frames_tres' is user-defined.
Computing uniform frame times from timestamps...
Assigning base layers per frame ticks...
Building map elements...
Error in prog_x_st[1:prog_bar_length] : 
  only 0's may be mixed with negative subscripts

[sample_track.zip](https://github.com/16EAGLE/moveVis/files/2037844/sample_track.zip)

**Comment by 16EAGLE** [comment]
Hi, sorry for the late reply. Unfortunately, I could not reproduce your error with the provided data. Running

```library(move); library(moveVis)
csv <- read.csv("/home/jakob/Downloads/sample_track.csv")
m <- move(x = csv$location.long, y = csv$location.lat, time = as.POSIXct(csv$timestamp), proj = CRS("+init=epsg:4326"), data = csv)
animate_move(m, out_dir = "/home/jakob/Downloads/", out_name = "test", out_format = "mov", frames_fps = 1)
animate_move(m, out_dir = "/home/jakob/Downloads/", out_name = "test2", out_format = "mov")
```

did not produce any error, instead outputs

```Checking prerequisites...
Detected library commands on this system: ffmpeg
Detected 'conv_dir' executable on this system: 'ffmpeg'
Warnung: Detected minimum temporal resolution of 1 seconds, but non-uniform timestamps, paths interpolation will be forced.
Warnung: 'frames_tres' set to 1 seconds, since undefined.
Warnung: Linear paths interpolation can massively distort movement, particularly non-movement periods!
Computing uniform frame times from timestamps...
Assigning base layers per frame ticks...
Building map elements...
Duration of output animation file: 00:00:02 (hh:mm:ss) [52 frames, 25 fps]
Drawing frames...
   |=====================================================================================================| 100% elapsed = 01m 23s
Total run time: 1.51 minutes
Done. 'test2.mov' has been saved to '/home/jakob/Downloads/'.
```

Are you running the most recent version of moveVis? How did you assemble your movment data input from your csv file? How does your animate_move() call looks like?

**Comment by 16EAGLE** [comment]
please reopen if needed.
