### ISSUE TITLE
RGB output map option orders stack layers wrongly

### ISSUE THREAD

**Issue by khufkens** [16EAGLE/moveVis#20]
https://github.com/16EAGLE/moveVis/blob/f0e6e245e9659eb0bc954d7b6aba5dc76d914911/R/animate_move.R#L1061

The layer ordering argument in ggRGB() is set to the wrong defaults (r=3,g=2,b=1) it should be:
r=1,g=2,b=3.

**Comment by 16EAGLE** [comment]
thanks, changed.
