### ISSUE TITLE
Issues with timestamps

### ISSUE THREAD

**Issue by rikwafo** [16EAGLE/moveVis#21]
Hi Jakob. I am back. I am having the following error message but it only occurs when i working on the movement certain individual not others. I have tried ordering the timestamps but still not working. Can you please advice me on what might be wrong and needs changing. Thanks once again for the package. 

m <- move(lu$location.long, lu$location.lat, proj=CRS("+proj=longlat +ellps=WGS84"), time = lu$timestamp, animal=lu$individual.local.identifier, data=lu)

Error in validityMethod(as(object, superClass)) : 
 The dataset includes timestamps that are not ascending

**Comment by 16EAGLE** [comment]
Sorry, from this I can't tell what the issue is. Could you provide subset of your data showing the same behavior?

**Comment by 16EAGLE** [comment]
Please reopen, if there are further questions on this issue.

**Comment by sarahefischer** [comment]
Hi, 
I am having the same issue where some individuals work, while others don't, and the code is the same. Below are the head and tail of my dataset. There are no NAs.

<img width="272" alt="screen shot 2018-09-17 at 4 42 25 pm" src="https://user-images.githubusercontent.com/43355530/45649233-bdfbef00-ba98-11e8-8e9a-8da0a9acbe1e.png">

<img width="287" alt="screen shot 2018-09-17 at 4 42 37 pm" src="https://user-images.githubusercontent.com/43355530/45649236-c0f6df80-ba98-11e8-8cf8-e7aea11204f3.png">

And here is the code. 
sevenJD$Date<- as.POSIXct(strptime(sevenJD$Date, "%m/%d/%Y"))

data_ani2 <- move(sevenJD$Longitude, sevenJD$Latitude, proj=CRS("+proj=longlat +ellps=WGS84"),
                       time = sevenJD$Date, animal=sevenJD$ID, data=sevenJD)
