### ISSUE TITLE
Code works for a subset of my dataset but gives error for another

### ISSUE THREAD

**Issue by DanPapageorgiou** [16EAGLE/moveVis#22]
Hi there,

I am using moveVis to visualize my data. My code works well for a subset of my dataset but gives error for another subset...

Any ideas about what could be going wrong?

Thanks,
Danai

> animate_move(dtanimwt, out_dir, conv_dir,
+              paths_mode = "true_data",
+              img_title = img_title, frames_nres = 10,
+              overwrite = TRUE)
Checking prerequisites...
Detected 'conv_dir' executable on this system: 'convert'
Warning: Detected minimum temporal resolution of 0.999000072479248 seconds, but non-uniform timestamps, paths interpolation will be forced.
Warning: 'frames_tres' set to 0.999000072479248 seconds, since undefined.
Warning: Linear paths interpolation can massively distort movement, particularly non-movement periods!
Computing uniform frame times from timestamps...
Error in seq.int(0, to0 - from, by) : wrong sign in 'by' argument
In addition: Warning messages:
1: In FUN(X[[i]], ...) : no non-missing arguments to min; returning Inf
2: In FUN(X[[i]], ...) : no non-missing arguments to min; returning Inf
3: In FUN(X[[i]], ...) : no non-missing arguments to min; returning Inf
4: In FUN(X[[i]], ...) : no non-missing arguments to min; returning Inf

**Comment by DanPapageorgiou** [comment]
or I also get 
...Computing uniform frame times from timestamps...
Error in `[<-.data.frame`(`*tmp*`, match(x$dt, t.df$dt), , value = list( : 
  missing values are not allowed in subscripted assignments of data frames

**Comment by 16EAGLE** [comment]
Please reopen, in case the issue is still relevant.
