### ISSUE TITLE
another timestamp issue

### ISSUE THREAD

**Issue by sarahefischer** [16EAGLE/moveVis#23]
Hi,
I am having the same issue where I can get the code for some individuals to work, while others don't, and the code is the same. Below are the head and tail of my dataset. There are no NAs. Let me know if you need more info... I was also wondering how I could add fixed "landmarks" (in my case, nest locations) on the map as you did in the white stork example with camera locations.

my error message is:
"Error in validityMethod(as(object, superClass)) : 
  The dataset includes timestamps that are not ascending"

<img width="272" alt="screen shot 2018-09-17 at 4 42 25 pm" src="https://user-images.githubusercontent.com/43355530/45694572-88551580-bb2d-11e8-834c-1927a317f610.png">

<img width="287" alt="screen shot 2018-09-17 at 4 42 37 pm" src="https://user-images.githubusercontent.com/43355530/45694581-8b500600-bb2d-11e8-9718-bcf63b92495b.png">

And here is the code.
sevenJD$Date<- as.POSIXct(strptime(sevenJD$Date, "%m/%d/%Y"))

data_ani2 <- move(sevenJD$Longitude, sevenJD$Latitude, proj=CRS("+proj=longlat +ellps=WGS84"),
time = sevenJD$Date, animal=sevenJD$ID, data=sevenJD)

Any help is much appreciated!
-Sarah

**Comment by 16EAGLE** [comment]
Hi Sarah,

it looks like your timestamps are not all in ascending order. Could you try `sevenJD[order(sevenJD$Date),]` before converting `sevenJD` to your move object?

To add static points annotated with a naming to the animation map, you can create a data.frame with an x, y an name column, e.g:

```
static_data <- data.frame(x = c(8.94,8.943), y = c(47.75,47.753), names = c("Site 1","Site 2"))
```
and assign this to the `static_data` argument in `animate_move()`. See the second example call in this example: http://movevis.org/reference/animate_move.html#examples

**Comment by sarahefischer** [comment]
Awesome, got both of those to work now -- thanks for the help!

**Comment by 16EAGLE** [comment]
Great, you're welcome.
