### ISSUE TITLE
Extend overlap not recognized

### ISSUE THREAD

**Issue by Lynx-H** [16EAGLE/moveVis#27]
Hello,

This is probably an issue on my end, and I apologize for posting it here, but I wasn't sure how to resolve it otherwise. When I run animate_move, I keep getting the error "Error in .local(x, y, ...) : extents do not overlap." I assume this refers to the move object and the base layer. However, the extent of the move object is fully within the extent of the base layer, and they are both in the same projection, and they do overlap when plotted together (or rather when I plot the location points used to inform the move object over the raster that I'm using for a base layer, as the move object does not plot over the raster).

The base layer is a single raster without any temporal element; I'm wondering if this could be causing the problem?

The animate_move function and extent & CRS information on the move object and base layer are as follows:

> animate_move(data_ani1, out_dir = ".", conv_dir = "convert", out_format = "gif", paths_mode="simple", layer=finland, layer_type="discrete")
Checking prerequisites...
Warning: Detected minimum temporal resolution of 7078 seconds, but non-uniform timestamps, paths interpolation will be forced.
Warning: 'frames_tres' set to 7078 seconds, since undefined.
Warning: Linear paths interpolation can massively distort movement, particularly non-movement periods!
Computing uniform frame times from timestamps...
Assigning base layers per frame ticks...
Error in .local(x, y, ...) : extents do not overlap

> extent(finland) #base layer, .tif raster object
class       : Extent 
xmin        : 20000 
xmax        : 739750 
ymin        : 6597200 
ymax        : 7836750 

> extent(data_ani1) # move object; code below
class       : Extent 
xmin        : 205828.2 
xmax        : 620020.2 
ymin        : 6677971 
ymax        : 7080056 

> crs(finland) #base layer, .tif raster object
CRS arguments:
 +init=epsg:3067 +proj=utm +zone=35 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs 

> crs(data_ani1) # move object; code below
CRS arguments:
 +init=epsg:3067 +proj=utm +zone=35 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs 

# For your reference, the code for the  move object is as follows:
data_ani1<- move(df6$X, df6$Y, proj=TM35FIN,  time = df6$Date_time_new, animal=df6$NAME, data=df6)

Thanks so much!

**Comment by 16EAGLE** [comment]
will check this, until then I recommend to test if the error still occurs if you use a geographic projection (longlat)

**Comment by 16EAGLE** [comment]
Could you report if you are still having this issue with the current version (0.9.9)? Thank you

**Comment by 16EAGLE** [comment]
please reopen of issue still exists
