### ISSUE TITLE
Error with geolocator data

### ISSUE THREAD

**Issue by Thiemokar** [16EAGLE/moveVis#29]
Moin,

Thanks for the outstading package.

Sadly I have a problem to animate a movie with my geolocation data.
I used the attached dataset.
The animation of the movie works, when I set the "frames_nmax" - value in the animate_move-function up to 146, but at 147 and higher the function gives the error:

Fetching 6 missing tiles
  |=====================================================================================================================| 100%
...complete!
Error in rgb(bm.df$red, bm.df$green, bm.df$blue, maxColorValue = if (any(maxValue(bm.down) >  : 
  Farbintensität -0.00120972 nicht in [0, 1]

But as the dataset has over 600 points it is useless for me to see only the first 146 points in the movie.
With another dataset this strange threshold is at "frames_nmax= 134"

Maybe someone has an idea about it?

thanks a lot,
Thiemo

[BF871_LTD.txt](https://github.com/16EAGLE/moveVis/files/2738734/BF871_LTD.txt)

**Comment by stmarcin** [comment]
Hello, 
As far as I know, "frames_nmax" defines number of 'time-frames', i.e. how many static plots ("snapshots") are used to prepare an animation. I guess 146 is the maximum number of plots which can be created given your time window and temporal output resolution. Thus, all your points are used, but the package 'interpolate' location of points using a regular time-window (or temporal resolution). It is what I understood from the package documentation. 
Hope it helps.
Best,
Marcin

**Comment by 16EAGLE** [comment]
Sorry for the late reply. Please note that moveVis has been rewritten with version 0.10.0 (which is on GitHub now) to make it more flexible. With that, `animate_move` has been replaced by `align_move`, `frames_spatial` and `animate_frames`. See the examples in the `README` and on [movevis.org](http://movevis.org) for details on how to use the new syntax.

Using the new version should solve your issue but please let me know if you encounter any problems.
