### ISSUE TITLE
out resulting animation to other formats

### ISSUE THREAD

**Issue by vestlink** [16EAGLE/moveVis#3]
Would it be possible to define the resulting animation format to a higher resolution format?

**Comment by 16EAGLE** [comment]
Thank you for your input. I added two new arguments to the animate_move() function (see the NEWS file): frames_width and frames_height two control the output resolution for the GIF file. Default is 600 x 600. Please check if that is what you thought about. Please note that only the resolution changes. Changing font sizes is not implemented yet but will be also soon. Therefore, the font appears very small if you higher the resolution. The changes are only available via GitHub at the moment and not the CRAN distribution.

**Comment by vestlink** [comment]
Beautiful :D
