### ISSUE TITLE
Error: Output file could not be found.

### ISSUE THREAD

**Issue by mattgonnerman** [16EAGLE/moveVis#30]
Hi, I am trying to use the below code to create a gif of my data downloaded/formatted from movebank. 

> #Get libraries 
> conv_dir <- "C:/Program Files/ImageMagick-7.0.8-Q16/convert.exe"
> 
> #Find out, which output file formats can be used
> get_formats()
> 
> #Specify output directory
> out_dir <- paste0(getwd())
> 
> #Specify some optional appearance variables
> img_title <- "Movement of the eastern wild turkey in Maine, USA"
> img_caption <- "Projection: Geographical, WGS84; Sources: Movebank 2013; Google Maps"
> 
> ####For a the 2018 greenfield birds, Winter to Nest movement 2018###
> animate_move(turkeygps, out_dir, out_name = "Greenfield Birds Animation Winter to Nest1", conv_dir = conv_dir, tail_elements = 10,
>              paths_mode = "true_data", frames_nmax = 530,
>              img_caption = img_caption, img_title = img_title,
>              log_level = 1, out_format = "gif")

When I set the frames_nmax = 50, the code runs fine and creates a gif. When I set frames_nmax = 0 or 530 (around the total number of frames) to generate a gif of the entire movement, I get the following output. (Edit: I did some additional tweaking and I get this code above around 200)

> Checking prerequisites...
> Warning: Detected minimum temporal resolution of 3434 seconds, but non-uniform timestamps, paths interpolation will be forced.
> Warning: 'frames_tres' set to 3434 seconds, since undefined.
> Warning: Linear paths interpolation can massively distort movement, particularly non-movement periods!
> Computing uniform frame times from timestamps...
> Assigning base layers per frame ticks...
> Copyright © 2019 Microsoft and its suppliers. All rights reserved. This API cannot be accessed and the content and any results may not be used, reproduced or transmitted in any manner without express written permission from Microsoft Corporation.
> Zoom: 11
> Fetching 6 missing tiles
>   |========================================| 100%
> ...complete!
> Building map elements...
> Duration of output animation file: 00:00:21 (hh:mm:ss) [520 frames, 25 fps]
> Drawing frames...
>    |==================================================| 100% elapsed = 31m 36sError: Output file could not be found.
> In addition: Warning message:
> In cmd.fun("batch.bat >nul 2>1") :
>   'batch.bat >nul 2>1' execution failed with error code 1

I'm having a bit of trouble interpreting the errors/warnings to diagnose what I am doing incorrectly or if this is something outside of my code.

Thanks

**Comment by 16EAGLE** [comment]
Sorry for the late reply. This issue should be solved with the latest major update to version 0.10.0, with which moveVis has been rewritten to make it more stable and flexible. With the new version, `animate_move` has been replaced by `align_move`, `frames_spatial` and `animate_frames`. See the examples in the `README` and on [movevis.org](http://movevis.org) for details on how to use the new syntax.

Please consider switching to the new syntax and let me know if you encounter any issues!
