### ISSUE TITLE
NA values in coordinates & Memory Exhausted errors

### ISSUE THREAD

**Issue by ljh2001** [16EAGLE/moveVis#31]
Hi, 

Thanks for the cool package, I'm excited to see animations of my data when I can figure out a couple issues. I've attached a small subset of my data, and the code that I used.

Code:
`library(moveVis)`
`library(move)`

`setwd("/users/ljh2001/Documents")`

`move_data<- read.csv("move_data.csv")`

`move_data$dt <- as.POSIXct(strptime(move_data$dt,`
                                  `  "%m/%d/%Y %H:%M:%S", tz = "UTC"))`

`move_data$individual<- as.factor(move_data$individual)`

`str(move_data)`

`m <- move( y = move_data$lon, x = move_data$lat, proj= CRS("+proj=longlat +init=epsg:6112"),`
                   `time = move_data$dt, data = move_data)`

`conv_dir <- get_libraries()`

`out_dir <- paste0(getwd(), "/Animations")`
`indi_names <- unique(move_data$individual)`

`img_title <- "Arctic Char"`
`img_sub <- paste0("including individuals",indi_names)`
`img_caption <- "Projection: Geographical, WGS84; Sources: Movebank 2013; Google Maps"`

`animate_move(m, out_dir, conv_dir = conv_dir, tail_elements = 10,
             paths_mode = "true_data", frames_nmax = 50,
             img_caption = img_caption, img_title = img_title,
             img_sub = img_sub, log_level = 1, out_format = "mov")`

Issue 1: Everything seems to be working until I attempt the animate_move function. The function begins to run, but eventually I get an error (Error in .local(obj, ...) : NA values in coordinates). This message caused me to look back at my data multiple times to check for potential typos, but I didn't find any. As far as I can tell, my data is set up the same as the example data (which does work). I did use a csv file in my code, but couldn't attach one here. Running `get_libraries()` gives me `[1] "convert" "ffmpeg" `, so I'm guessing the external libraries downloaded fine.

Issue 2: As I mentioned above, this is only a small sample of a much larger dataset (~250000 acoustic detections). When I try to run a larger set say (~3000 detections or the entire thing) I get a memory exhausted error. I also get a warning about non-uniform timestamps (I get that warning when the above code runs too). Could this just be related to Issue 1, or is it too computationally intense to create animations for that many detections with non-uniform timestamps?

Thanks for the help, and for creating such a cool package. I hope we can get it to work for me! Please let me know if I can provide other helpful information.

[move_data.xlsx](https://github.com/16EAGLE/moveVis/files/2814622/move_data.xlsx)

![myscript](https://user-images.githubusercontent.com/47194924/52015087-2929e900-24af-11e9-9861-762cbbb43111.JPG)

**Comment by 16EAGLE** [comment]
Sorry for the late reply, I waited answering since I've been working on a new version of moveVis restructuring the package. 

With the new version, `animate_move` has been replaced by `align_move`, `frames_spatial` and `animate_frames` to separate data preparation, frames creation and turning frames into animations. This way, you gain more control about how your data are handled and what causes possible problems. See the examples in the `README` and on [movevis.org](http://movevis.org) for details on how to use the new syntax.

Please consider switching to the new syntax and let me know if you encounter any issues!
