### ISSUE TITLE
Error in idData not trackID

### ISSUE THREAD

**Issue by dombomb72** [16EAGLE/moveVis#34]
When I try to run this line of code, I get this error

> p <- move(pdfhvtrack$lon, pdfhvtrack$lat, proj=CRS("+proj=longlat +ellps=WGS84"),
+           time = pdfhvtrack$dt, animal=pdfhvtrack$individual, data=pdfhvtrack)
Error in validityMethod(as(object, superClass)) : 
  Order of objects in the idData is not the same as in the trackId
In addition: Warning messages:
1: Unknown or uninitialised column: 'citation'. 
2: Setting row names on a tibble is deprecated. 

> head(pdfhvtrack)
# A tibble: 6 x 5
    lon   lat population individual dt                 
  <dbl> <dbl> <fct>      <fct>      <dttm>             
1  41.4 -91.0 Pool 16    T12414     2018-07-31 00:00:00
2  41.4 -91.0 Pool 16    T12414     2018-09-25 00:00:00
3  41.5 -90.6 Pool 16    T12414     2018-11-09 00:00:00
4  41.5 -90.6 Pool 16    T12415     2018-06-12 00:00:00
5  41.5 -90.6 Pool 16    T12415     2018-06-28 00:00:00
6  41.5 -90.6 Pool 16    T12415     2018-09-18 00:00:00

> str(pdfhvtrack)
Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	255 obs. of  5 variables:
 $ lon       : num  41.4 41.4 41.5 41.5 41.5 ...
 $ lat       : num  -91 -91 -90.6 -90.6 -90.6 ...
 $ population: Factor w/ 4 levels "Pool 14","Pool 16",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ individual: Factor w/ 102 levels "T12414","T12415",..: 1 1 1 2 2 2 2 3 3 4 ...
 $ dt        : POSIXct, format: "2018-07-31" "2018-09-25" "2018-11-09" "2018-06-12" ...

**Comment by 16EAGLE** [comment]
Hmm, just from the code I do not know how to avoid the error and warnings here. Since this is a `move` package related issue, maybe it’s developer @bart1 can help? You could also consider opening this issue at Bart’s `move` repository: https://gitlab.com/bartk/move/issues

**Comment by bart1** [comment]
Hard to say what exactly is happening I agree that the error message does not seem to informative and might indeed relate to move. Would you be able to make a reproducible example?
