### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by gcarrascoe** [16EAGLE/moveVis#36]
Hi,

I have this problem when installing the package 

<img width="822" alt="screen shot 2019-02-23 at 11 36 54 pm" src="https://user-images.githubusercontent.com/7484990/53296584-ba4a6200-37c6-11e9-8f43-3e1943433bbf.png">

It seems that slippymath API names just changed. 

Thanks,
Gabriel

**Comment by 16EAGLE** [comment]
Thanks, should be fixed now.
