### ISSUE TITLE
Error in rep(x[3], diff(x[1:2]) + 1) : invalid 'times' argument

### ISSUE THREAD

**Issue by JepsonNomad** [16EAGLE/moveVis#38]
Hey Jakob - I'm having an issue with the `frames_spatial()` step. I can make a move object using `df2move()` and then regularize the location data with `align_move()`, but when I try to run `frames_spatial()` I get the error above. It's weird though because the movement data processes fine (as per the progress bar, which hits 100% after 8 seconds). A few seconds after "Assigning raster maps to frames..." prints, the error pops up. My `r_times` argument is in POSIXct format and is the same length as `r_list`. 

This error only appears when my own raster data are included. If I use `frames_spatial()` with location data only, the function works and I can proceed with `animate_frames()`.

**Comment by 16EAGLE** [comment]
Hi, thanks for sharing this issue. Could you provide a reproducible code example that includes the generation of your `r_times` and that produces the error? Then I can try to recreate the error with some dummy rasters. Otherwise I will have difficulties to identify the source of the error.

**Comment by JepsonNomad** [comment]
`r_times` is generated based off of a file list. That list looks like this:
```
rasterfiles = c("data/VI/reprojected/Wheeler_Mask_VI_2016_001.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_017.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_033.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_049.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_065.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_081.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_097.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_113.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_129.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_145.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_161.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_177.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_193.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_209.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_225.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_241.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_257.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_273.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_289.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_305.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_321.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_337.tif","data/VI/reprojected/Wheeler_Mask_VI_2016_353.tif")

```
Apologies for that disgusting mess of things but I don't know a better way to share that part of this. Anyway, from that, you can generate an r_times object using:

```
r_times = str_split(rasterfiles,pattern = "_") %>% 
  map_chr(`[`, 5) %>%
  substr(start = 1, stop = 3)
r_times = paste("2016", r_times, sep="-") %>%
  as.POSIXct(format="%Y-%j", origin = "2016-01-01", tz = Sys.timezone())
r_times

```

**Comment by 16EAGLE** [comment]
Unfortunately, I could not reproduce the error. Could you give me something more reproducible, the exact code that causes the error? Easiest for me would be to have also the movement data you use since I could not reproduce the error with the example data. You could test if the error occurs also with a small subset of your data and share only that (or send a data snippet privately if that helps). Raster data I can replace with dummys since I think their shape is not related to the issue.

**Comment by JepsonNomad** [comment]
The error persists with a subset of the data. I can pass along something privately. What's the best way to do that?

**Comment by 16EAGLE** [comment]
You can send me the subset and the code that produces the error to my mail address listed in line 8 of the description file: https://github.com/16EAGLE/moveVis/blob/master/DESCRIPTION

Would be nice for me to sort out this error since others reported it too and this way it would be easy for me to track it down, so thanks in advance for sharing the subset.

**Comment by JepsonNomad** [comment]
Right on - check your email. Looking forward to the solution.

**Comment by 16EAGLE** [comment]
Thanks. This should be resolved with the latest commits. Could you reinstall and check, if the error is gone?

**Comment by StephPeriquet** [comment]
Hi there, Just tested with the new version and it seems that the problem is gone. Thanks!

**Comment by 16EAGLE** [comment]
I just discovered another error related to this. Thus, the time assignment section has been rewritten. Now `frames_spatial` should work for both `fade_raster = T` and `fade_raster = F`.

**Comment by JepsonNomad** [comment]
That did the trick! Thanks.
