### ISSUE TITLE
New df2move error on trackid

### ISSUE THREAD

**Issue by johnij** [16EAGLE/moveVis#41]
Hi,

I love your map animation and worked several hours getting it to go. But it was worth the try.
I wanted to use some personal data that i need to run on the maps. while converting my data frame using df2move i get this error. I tried to factor the lodi which is my track id, but that didnt work either. Can you tell me where/what i am missing out?

Thanks

Error  enclosed------------------------------------------------------------------------

Error: Must use a vector in `[`, not an object of class matrix.
Call `rlang::last_error()` to see a backtrace

Error Ends-----------------------------------------------------------------------
library(moveVis)
library(move)

df <- read_excel("c:/users/hp/desktop/bird/testdata.xlsx")

#df$loco_id <- as.factor(df$loco_id)

df <- df[!duplicated(df),]

y <- df2move(df,
        proj = "+init=epsg:4326 +proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0", 
        x = "lon", y = "lat", time = "time", track_id = "lodi")

[testdata.xlsx](https://github.com/16EAGLE/moveVis/files/2954774/testdata.xlsx)

**Comment by 16EAGLE** [comment]
Hi, thanks for reporting this error and the reproducible example+test data. The issue should be fixed with the latest commit – please reinstall `moveVis` with `install_github("16eagle/moveVis")`.
