### ISSUE TITLE
is it possible to skip gaps?

### ISSUE THREAD

**Issue by francisvolh** [16EAGLE/moveVis#43]
Hello @schwalbwillmann! I have been playing with you moveVis package and I think is great! Excellent job! 
But I remember the previous version had an option to "skip gaps" in time. It never really worked for me, so I wonder if this newest version may be able to do it? 
My track are movement data on nesting birds, so I have cleaned the data and only have the moving "points". That definitely defies the idea of "uniform" time scale, but I wonder if there is way around it when aligning (I supposed that is the right moment to do it). I guess I could also make several animations per individual trip but if having several birds (as of now I have worked only with one individual in a 3 day period) the times at the nest will differ for sure. 
Anyway, jut wanted to bug you with this maybe you have some ideas, or just sad news saying movisVis wont be able to do it! hehehe
Thanks either way!
Francis

**Comment by francisvolh** [comment]
Hi! I have been thinking about this, and I wonder if there is the possibility of detecting the positions of the frames that contain the "gap times" (maybe detecting where the big timeLags are and then locating the "position" of the frames, but they may after aligning this will completely lost?) and then sub-setting the frames use with the animate_frames. 
Anyway, this was a shot in the dark. Thanks for any input!

**Comment by 16EAGLE** [comment]
Hi, this could be done by subsetting your movement data by the time gaps, then create the frames independently for each subset. Afterwards, you could put all the frames together to create a single animation that skips the gaps.

Here is an example with the `moveVis` example movement data:

```R
library(moveVis)
library(move)
data("move_data")
```
Assumed, `move_data` contains a gap between `2018-05-15 14:09:18 UTC` and `2018-05-15 16:31:11 UTC` (could be days etc. as well). You could subset your data into several move objects per time coverage, e.g.:

```R
m1 <- subset_move(move_data, from = min(timestamps(move_data)), to = "2018-05-15 14:09:18")
m2 <- subset_move(move_data, from = "2018-05-15 16:31:11", to = max(timestamps(move_data)))
```

Now, you'd just need to align them by equal properties:

```R
m.aligned <- lapply(list(m1, m2), function(x) align_move(x, res = 240, digit = 0, unit = "secs"))
```
...and call `frames_spatial` for each move object with the overall extent of your move data, for example:

```R
frames <- lapply(m.aligned, function(x) frames_spatial(x, path_colours = c("red", "green", "blue"),
                                                       map_service = "osm", map_type = "watercolor",
                                                       ext = extent(move_data)))
```
Frames now is a list of two lists of frames (one list for each `move` object), which you may just unlist to combine the frames of both move objects before animating it:
```R
frames <- unlist(frames, recursive = F)

# add overall time stamps and progress bare
frames <- add_timestamps(frames, m = moveStack(m.aligned), type = "label")
frames <- add_progress(frames)

# animate frames
animate_frames(frames, out_file = "test.gif")
```

![result](https://user-images.githubusercontent.com/23257860/54675967-f17b0d00-4aff-11e9-8abe-52676f2796fa.gif)

Does this answer your question, is this what you are looking for?

**Comment by francisvolh** [comment]
This sounds perfect Jakob. I just need to find a quick way to subset my data. Thanks a lot for the help!

**Comment by 16EAGLE** [comment]
Great. If you know the time stamps defining the gap, you could just use `subset_move`.

**Comment by francisvolh** [comment]
Sure, I could do it manually. But I will try to extract them as vectors and see if its useful in the future!

Thanks again!
