### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by DarcyDM** [16EAGLE/moveVis#67]
Hello, I'm getting an error on loading the package. Install is always successful, then error on loading is something to do with 'sf' and object group_map (from 'dplyr', I think). I am using R version 3.5.2. I tried uninstalling / reinstalling the package, also uninstalling / reinstalling / updating 'sf' and 'dplyr' with no change in the error message. 

Install and load messages below: 

> **install.packages("moveVis")**
Installing package into ‘C:/Users/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/moveVis_0.10.2.zip'
Content type 'application/zip' length 3039027 bytes (2.9 MB)
downloaded 2.9 MB
package ‘moveVis’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\AppData\Local\Temp\Rtmpgzv1d3\downloaded_packages

> **library("moveVis")**
Error: package or namespace load failed for ‘moveVis’:
 .onLoad failed in loadNamespace() for 'sf', details:
  call: get(genname, envir = envir)
  error: object 'group_map' not found
In addition: Warning message:
package ‘moveVis’ was built under R version 3.5.3 

When I try to call df2move() it says it cannot find the function. 

Maybe this is an issue on my end, but I haven't found any help online and am stuck. Thanks for any help you can give me!

**Comment by DarcyDM** [comment]
Thanks for the reply. Yep, I needed to update dplyr. * facepalm * 

Awesome package! Looking forward to playing around with it more. Here is a bear slowly emerging from her winter den. https://imgur.com/xoIYBxn

**Comment by DarcyDM** [comment]
Thanks for the reply. Yep, I needed to update dplyr. * facepalm *

Awesome package! I'm looking forward to playing around with it more. Here is a bear slowly emerging from her winter den.

 https://imgur.com/xoIYBxn

**Comment by 16EAGLE** [comment]
Great that it works now and a nice animation! Please let me know in case you encounter any further issues.
