### ISSUE TITLE
Processing times for large data frame and multiple individuals

### ISSUE THREAD

**Issue by l-peel** [16EAGLE/moveVis#7]
I have a large data frame (>100,000 positions and 10-20 individuals) that I am currently running through animate_move(). It has been processing for close to 30 hours, and the outputs:

[1] "[LOG]:  Creating PNG frame files (this may take a while; depending on the spatial resolution of the basemap)..."
[1] "[LOG]:  Creating GIF file..."

have repeated 8 times so far. Just wondering if this is usual for a data frame of this size, or the repetitions signify multiple unsuccessful attempts at compiling the GIF final file?

Thanks!

**Comment by 16EAGLE** [comment]
Thank you for your message. moveVis is just capable of visualizing data, its focus is not to preprocess them. Therefore, depending on your data you might need to define a preselection of points over a specific time range that you can hand over to animate_move(). Presumed you have not changend the frame rate (standard is 0.4 seconds per frame), in your case, the input of raw data with more than 100.000 position would cause animate_move with the preset keywords to try to create a GIF with a length of around 11 hours (((100000*0.4)/60)/60). I recommend you to select those temporal ranges you would like to animate to make the animation shorter. 

Beside that there are a few options to deal with long data, e. g. using the argument "frames_nres" (interval of which frames of all frames should be used, nth element, default is 1, then every frame is used, if set to 2, only every second frame is used). However, this should only be used if the positions are very close and the gaps can easily be interpolated by animate_move.

The repetition of the GIF creation is normal. If long GIFs are created, animate_move() produces several sub-GIFs and combines them in the end.

**Comment by l-peel** [comment]
Thanks very much for your reply - I will try again using a smaller data set.
