### ISSUE TITLE
Higher resolution map as background

### ISSUE THREAD

**Issue by DanPapageorgiou** [16EAGLE/moveVis#73]
Hi there,

I am trying to make an animation of my study birds moving in a area of 70*70m. I want to use as background a  satellite image. Mapbox map though is very low res in such scale. Is there an alternative? I thought of downloading a  map using ggmap  and put this is the frames_spatial function but it doesn't seem to be feasible. Are there any alternatives to this?

Thanks,
Danai

**Comment by 16EAGLE** [comment]
Hi Danai,

sorry for the late reply. It is possible to include any raster map using the `r_list` and `r_times` argument of `frames_spatial`. If you want to provide a static map, just provide a single RGB `rasterStack` to `r_list`.

Hope this helps or is still relevant.

Best,
Jakob
