### ISSUE TITLE
HTTP error 401

### ISSUE THREAD

**Issue by anaveda** [16EAGLE/moveVis#74]
Hi,
I am trying to use mapbox but I am getting this error:
>frames <- frames_spatial(m, path_colours="red",
                         map_service = "mapbox", map_type = "satellite",map_token="R2D2", alpha = 1)

Error in curl_download(url = url, destfile = file) : HTTP error 401.

I wonder if anybody knows what it means and how to fix it.

Thanks

Adrian

**Comment by 16EAGLE** [comment]
Hi Adrian,

`HTTP 401` means `unauthorized` – if you are trying to run `frames_spatial` with `map_token = "R2D2"` as access token, than that might be the reason why it does not work. You need to insert a token connected to your mapbox account here. You find your token(s) in the section "Tokens" after logging in to your mapbox account. Copy the token and hand it as a character to the `map_token` argument.

![mapbox](https://user-images.githubusercontent.com/23257860/65755486-7e3bfe80-e113-11e9-831a-b7566e35cc41.png)

**Comment by anaveda** [comment]
Thanks Jacob. Now it worked. All the best,

**Comment by nmasto** [comment]
Dear Jacob,

Has anything changed with map box since you last addressed this comment? I'm having the exact same issue and I've made my map tokens (both public and private ones). Yet, I'm still only able to download "satellite".

Code snippet here if needed:

```
frames <- frames_spatial(mdat, 
                        trace_show = FALSE, 
                        equidistant = FALSE,
                        map_service = "mapbox", 
                        map_type = "satellite",
                        map_token = "sk.eyJ1Ijoibm1tYXN0bzQyIiwiYSI6ImNsNDhsYjloejBtZ3YzaXBuN3h5d29neTAifQ.rb14JF1VbEffXIu_R4BPPQ",
                        path_size = 3, 
                        path_legend = FALSE,
                        r_type = "gradient",
                        )
```

Best,

**Comment by tzumwal** [comment]
I am having the same issue as Nick. Any info is much appreciated!

**Comment by Aliya-Caldwell** [comment]
I am also having this issue.

**Comment by andrewdigby** [comment]
Same here.
