### ISSUE TITLE
Track jumps when crossing the -180/180 Longitude Boundary

### ISSUE THREAD

**Issue by cpuguru** [16EAGLE/moveVis#75]
I'm using moveVis to create animations of ship movements around the globe.

When transitioning from -180 to 180 the path jumps across the screen taking the long route around rather then creating the much shorter segment.

Is there a work-around for these jumps?

**Comment by 16EAGLE** [comment]
Thanks for that finding, I will look into it

**Comment by cpuguru** [comment]
Here's a link to a dataset that crosses the boundary if that helps...
https://www.researchvessels.org/images/shipdata.RDATA

**Comment by cpuguru** [comment]
Trying to implement the st_wrap_dateline() call against the data. Looks like I have to convert the data to a Line to do so?

**Comment by cpuguru** [comment]
I submitted the dilemma to StackOverflow & got a response on how to remedy the track portion.

Now I need to figure out how to coerce the results from LINESTRINGS to POINTS so that I can use them with MoveVis.

https://stackoverflow.com/questions/58998580/how-to-remedy-a-path-that-crosses-the-international-dateline-with-r

**Comment by johnsonamy24** [comment]
How do you remedy the track portion? I am having the same issue

**Comment by 16EAGLE** [comment]
Please see #82 for a fix to this in case it is still relevant for you.
