### ISSUE TITLE
Adjusting point & text size when creating hi-res images

### ISSUE THREAD

**Issue by cpuguru** [16EAGLE/moveVis#76]
When I use ggsave to create a 4000x2000 resolution image for a spherical display, the label text & point sizes are super small in relation to the basemap background image.

Not sure how to scale/adjust that when saving a Move object to a PNG.

**Comment by 16EAGLE** [comment]
Could you give me a bit of context, for which purpose you use `ggsave` here or what your aim is? Generally, changing the argument `dpi` of `ggsave` will have an effect on how large text/points are displayed compared to width/height.

**Comment by cpuguru** [comment]
Thanks - I halved the length & width & doubled the dpi & I think that will suffice. Thanks for the info!
