### ISSUE TITLE
Check presence of directory of output file at the beginning

### ISSUE THREAD

**Issue by damianooldoni** [16EAGLE/moveVis#79]
Thanks for this nice package. A small enhancement idea:

While running the code in http://movevis.org/#get-started, I get this error:
> Error in gifski(images, gif_file = gif_file, width = width, height = height,  : 
  Target directory does not exist:C:/full/path/to

It would be nice to check the presence of directory BEFORE running all processing in `animate_frames`: in this way the user doesn't wait a lot of time to encounter an error it could be easily detected at the very beginning.

About the snippet in get started section, my suggestion is to set `outfile` as follows:
```r
animate_frames(frames, out_file = "moveVis.gif")
```
so that it works and first-time user is happy :tada: 

What do you think? Does it make any sense? Thanks again for this package.

**Comment by 16EAGLE** [comment]
Thanks for these suggestions – I changed the it accordingly.
