### ISSUE TITLE
error using animate_frames after running use_multicore

### ISSUE THREAD

**Issue by dwwolfson** [16EAGLE/moveVis#80]
I can use `animate_frames()` fine normally, but if I try to run it after running `use_multicore()` I get the error `Error in get(name, envir = envir) : object 'quiet' not found`.

Is `quiet` from a dependency or should it be in base R?

**Comment by 16EAGLE** [comment]
This should have been fixed with 1ff24728. Could you reinstall from GitHub and see, if the issue persists? Nice that you are testing the development version – feel free to let me know if you find issues with parallelizing or something is not working as expected!

**Comment by dwwolfson** [comment]
Thanks for the reply. Yes, I've reinstalled with the dev version from Github (0.10.4) and the code is updated as shown in `1ff2472`. Still getting the same error though.

**Comment by 16EAGLE** [comment]
OK, after a change, could you reinstall and check if the problem is now gone?

**Comment by dwwolfson** [comment]
Yes, that seems to have resolved the issue. Thanks very much for your help!
