### ISSUE TITLE
Error in match.arg(progress.bar, c("txt", "tk", "none"))

### ISSUE THREAD

**Issue by WhitneyH1317** [16EAGLE/moveVis#84]
Hi, I've gotten the above error when attempting to run the frames_spatial command, both on my data and the example dataset provided by the moveVis library. 
i.e.
frames <- frames_spatial(move_data, path_colours = c("red", "green", "blue"),
                         map_service = "osm", map_type = "watercolor", alpha = 0.5)
or
frames_spatial(move_data, path_colours = c("red", "green", "blue"),
                        map_service = "osm", map_type = "streets", map_res = 0.8, equidistant = F)
and any variation in the example moveVis package. 

This is what I get when attempting to run the above command:

Checking temporal alignment...
Processing movement data...
Approximated animation duration: ≈ 7.52s at 25 fps for 188 frames
Retrieving and compositing basemap imagery...
Error in match.arg(progress.bar, c("txt", "tk", "none")) : 
  'arg' should be one of “txt”, “tk”, “none”

Please advise!

**Comment by pham-thomas** [comment]
I'm also running into this issue just running the Getting Started example. Seems to be breaking on **frames_spatial()**. I dug into the source code and for me it seems to be breaking here but beyond that I can't figure out any further what's going on . 

`    r_list <- .getMap(gg.ext, map_service, map_type, map_token, 
      map_dir, map_res, m.crs = crs(m))`

**Comment by pham-thomas** [comment]
Hallelujah! I was able to get it working. I traced the error to a call to pboptions() which comes from pbapply and looks like is imported from moveVis. I installed the package pbapply to see if it would make a difference and looks like it worked!

**Comment by WhitneyH1317** [comment]
Oh awesome!! I was really hoping you'd write back with an update! I'm going
to give this a try, thank you so so much!

- Whitney

**Comment by 16EAGLE** [comment]
Hi, sorry for the late reply. This is most certainly related to the installed version of `pbapply`. Was the issue resolved by updating `pbapply` as @pham-thomas suggested?
