### ISSUE TITLE
Error with duplicated timestamps

### ISSUE THREAD

**Issue by frewom** [16EAGLE/moveVis#85]
Hi, 

I have tried to find a solution to this problem in the other answers but i cannot seem to. Does this package work when you have multiple ID's with the same time stamp. When I attempt to use df2move() I get the error 

`Error in validityMethod(as(object, superClass)) `: 
 `The dataset includes double timestamps first one:2012-01-01)`

A subset of my dataframe:
                                      `      ID       date  longitude   latitude
147   gsmp01361_108093 2012-01-01  -83.67805  -6.739897
292   gsmp01362_108096 2012-01-01  -81.52966  -2.567828
345   gsmp01364_108106 2012-01-01  -86.71840  -4.344050
148   gsmp01361_108093 2012-01-02  -83.34108  -6.598395
293   gsmp01362_108096 2012-01-02  -81.55895  -2.329897
346   gsmp01364_108106 2012-01-02  -86.63386  -4.526737
559   gsmp01370_112557 2012-01-02  -82.09367   4.719112
1767  gsmp01431_107714 2012-01-02  -81.56351   7.717694
2396  gsmp01439_107723 2012-01-02 -110.53296  24.204923
2493  gsmp01440_107725 2012-01-02  -81.61740   7.726292`

My code:

`Mtracks <- df2move(tracks, 'longitude', 'latitude', 'date', track_id = 'ID', proj = proj4string)`

This seems to work when I have one track with no duplicated days, but ideally I would like to combine them. 
Any suggestions?

Thank you!

**Comment by clairemas0n** [comment]
Hi @frewom - did you work out a solution to this issue? Thanks
