### ISSUE TITLE
Temporal resolution diverging error on regularly-spaced data

### ISSUE THREAD

**Issue by taoofcoffee** [16EAGLE/moveVis#95]
I am trying to visualize the movement of some animals, but I am running into an error when I try to make a spatial frame:

```
LillunnFrame <- frames_spatial(LillunnMove, 
                            map_service = "osm",
                            map_type = "terrain_bg",
                            trace_show = T)
```

`Error: The temporal resolution of 'm' is diverging. Use align_move() to align movement data to a uniform time scale with a consistent temporal resolution.`

It is my understanding that this error arises when there are temporal gaps in the "time" column of the data. I have one week of data, with a temporal period of one hour between locations, 24 locations per day. I have 168 observations with no irregularities in the temporal spacing. How is my data being flagged as diverging? Here is the head and tail of my GPS data before it's made into a move object:

` head(Lillunn)`
# A tibble: 6 x 9
        x       y GMT.date            ID    burst PubName Height   DOP Bearyear  
    <dbl>   <dbl> <dttm>              <fct> <fct> <fct>    <dbl> <dbl> <fct>     
1 1433547 6804747 2019-08-14 03:00:00 W1011 W1011 Lillunn   549.   8.4 W1011_2019
2 1433877 6804197 2019-08-14 04:00:00 W1011 W1011 Lillunn   564.   2.4 W1011_2019
3 1433879 6804197 2019-08-14 05:00:00 W1011 W1011 Lillunn   563    1.6 W1011_2019
4 1433885 6804192 2019-08-14 06:00:00 W1011 W1011 Lillunn   569.   2.8 W1011_2019
5 1433877 6804191 2019-08-14 07:00:00 W1011 W1011 Lillunn   560.   2.6 W1011_2019
6 1433870 6804196 2019-08-14 08:00:00 W1011 W1011 Lillunn   566.   2.4 W1011_2019

` tail(Lillunn)`
# A tibble: 6 x 9
        x       y GMT.date            ID    burst PubName Height   DOP Bearyear  
    <dbl>   <dbl> <dttm>              <fct> <fct> <fct>    <dbl> <dbl> <fct>     
1 1433394 6806368 2019-08-20 22:00:00 W1011 W1011 Lillunn   582.   2.2 W1011_2019
2 1433438 6806458 2019-08-20 23:00:00 W1011 W1011 Lillunn   566.   2   W1011_2019
3 1433435 6806455 2019-08-21 00:00:00 W1011 W1011 Lillunn   565.   2.8 W1011_2019
4 1433394 6806353 2019-08-21 01:00:00 W1011 W1011 Lillunn   611.   2.2 W1011_2019
5 1433398 6806363 2019-08-21 02:00:00 W1011 W1011 Lillunn   605.   4.2 W1011_2019
6 1434043 6806476 2019-08-21 03:00:00 W1011 W1011 Lillunn   552.   2.6 W1011_2019

And the move object I created from the tracks:

```
LillunnMove <- df2move(Lillunn,
                        proj = "+init=epsg:3021",
                        x = "x", y = "y",
                        time = "GMT.date")
```

`LillunnMove`
class       : Move 
features    : 168 
extent      : 1424098, 1437897, 6802113, 6819016  (xmin, xmax, ymin, ymax)
crs         : +proj=tmerc +lat_0=0 +lon_0=15.8082777777778 +k=1 +x_0=1500000 +y_0=0 +ellps=bessel +units=m +no_defs 
variables   : 3
names       :       x,       y,       time 
min values  : 1424098, 6802113, 1565744400 
max values  : 1437897, 6819016, 1566349200 
timestamps  : 2019-08-14 03:00:00 ... 2019-08-21 03:00:00 Time difference of 7 days  (start ... end, duration) 
sensors     : unknown 
indiv. data :  
indiv. value:  
date created: 2020-07-21 21:13:28 

When I plot the move object, it looks like all the features are present. 

`plot(Lillunn)`

![image](https://user-images.githubusercontent.com/8749759/94941023-9d166300-04d4-11eb-997f-84efc6722dec.png)

Finally, even though I know my data are regularly spaced, I try to use align_move before making a spatial frame and get yet another error:

`LillunnMove <- align_move(LillunnMove, res = 3600, digit = 0, unit = "secs")`

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'moveStack': longitude > 360
```

Appreciate any feedback/help I can get here. I have 47 animals I'd like to visualize.

**Comment by marcoscarloseduardo** [comment]
Hi, please check if your variable "GMT.date" is in the format "POSIXct". That error appeared to me when my time variable was datetime but not explicitly "POSIXct".

Maybe Lillunn$GMT.date<- as.POSIXct(Lillunn$GMT.date) solves the problem

Best regards

**Comment by taoofcoffee** [comment]
> 
> 
> Hi, please check if your variable "GMT.date" is in the format "POSIXct". That error appeared to me when my time variable was datetime but not explicitly "POSIXct".
> 
> Maybe Lillunn$GMT.date<- as.POSIXct(Lillunn$GMT.date) solves the problem
> 
> Best regards

Hi and thanks for the reply. I double-checked and the GMT.date column is in the POSIXct format.

**Comment by marcoscarloseduardo** [comment]
Do you have repeated dates and times? If so, modify one second so that there are not two events within the series with the same datetime.

**Comment by taoofcoffee** [comment]
> 
> 
> Do you have repeated dates and times? If so, modify one second so that there are not two events within the series with the same datetime.
> 
> and you can try this to check the time gap:
> unique(timestamps(LillunnMove))
> unique(unlist(timeLag(LillunnMove, units = "secs")))
> 
> LillunnMove <- align_move(LillunnMove, res = unique(unlist(timeLag(LillunnMove, units = "secs")))[1], unit = "secs")

Hi, I ran the code and all of the timestamps (168) are unique. The second line of code gave me 

`[1] 3600 7200`

When I tried `LillunnMove <- align_move(LillunnMove, res = unique(unlist(timeLag(LillunnMove, units = "secs")))[1], unit = "secs")`

I got the same error message described previously: `Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'moveStack': longitude > 360`

**Comment by marcoscarloseduardo** [comment]
Hi, it seems that some record is missing, so the interval is not uniform (3600 vs 7200).

You could check if you can register the missing record(s), or try to do the interpolation every 2 hours.

If it doesn't work, can you upload the data (Lillunn) to try to reproduce the error?

**Comment by taoofcoffee** [comment]
I changed the resolution to 7200 seconds in the align_move function and it worked. Thank you very much for the reply! (It's a little annoying to have to "throw away" about half of my data (as there was only one missing record), but at least I have managed to make the spatial frame and animate it.)

**Comment by marcoscarloseduardo** [comment]
If only one record is absent perhaps it would be better to duplicate the previous one and modify the time to complete the time series than to resign half of the records.

Good luck!
